[package]
name = "cosmic-protocols"
version = "0.1.0"
edition = "2021"
documentation = "https://pop-os.github.io/cosmic-protocols/"
repository = "https://github.com/pop-os/cosmic-protocols"
authors = ["Victoria Brekenfeld <github@drakulix.de>"]
license = "GPL-3.0"
keywords = ["wayland", "client", "server", "protocol", "extension"]
description = "Generated API for the COSMIC wayland protocol extensions"
categories = ["gui", "api-bindings"]
readme = "README.md"

[dependencies]
wayland-scanner = "0.30.0-beta.10"
wayland-backend = "0.1.0-beta.10"
wayland-protocols = "0.30.0-beta.10"
wayland-client = { version = "0.30.0-beta.10", optional = true }
wayland-server = { version = "0.30.0-beta.10", optional = true }
bitflags = "1.0"

[dev-dependencies]
png = "0.17.5"
smithay = { git = "https://github.com/Smithay/smithay", rev = "625cbca5", default-features = false, features = ["backend_drm", "backend_egl", "renderer_gl", "renderer_multi"] }

[features]
default = ["client", "server"]
client = ["wayland-client", "wayland-protocols/client"]
server = ["wayland-server", "wayland-protocols/server"]
